version: 9.4.2-nightly-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
skip_tags: true
max_jobs: 1
image: Visual Studio 2019
clone_depth: 1
build_script:
- ps: |-
    # Version number
    $BUILD_NUMBER = [int]$Env:APPVEYOR_BUILD_NUMBER
    $BUILD_SUFFIX = "nightly"

    # Branch
    $BRANCH = "$Env:APPVEYOR_REPO_BRANCH"
    $Env:DOCFX_SOURCE_BRANCH_NAME = "$BRANCH"

    # Output directory
    $Env:ARTIFACT_DIR = ".\artifacts"
    $dir = New-Item -type directory $env:ARTIFACT_DIR
    $dir = $dir.FullName

    # Verbosity
    Write-Host "Build: $BUILD_NUMBER / Branch: $BRANCH"
    Write-Host "Artifacts will be placed in: $dir"

    # Check if this is a PR
    if (-not $Env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
        # Rebuild documentation
        Write-Host "Commencing complete build"
        & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER -DocsPath ".\docs" -DocsPackageName "dsharpplusnextgen-docs"
    }
    else
    {
        # Skip documentation
        Write-Host "Building from PR ($Env:APPVEYOR_PULL_REQUEST_NUMBER); skipping docs build"
        & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER
    }
artifacts:
- path: artifacts\*.nupkg
- path: artifacts\dsharpplusnextgen-docs.tar.xz
deploy:
- provider: NuGet
  server:
  api_key:
    secure: XtptFAacNyLULAZaRpAGh/e28Q1jkZSmODo4d2dkAUamFSsTQa3MzJAo4lSC1Vlb
  skip_symbols: true
#- provider: NuGet
#  server: https://nuget.pkg.github.com/Aiko-IT-Systems/index.json
#  username: Lulalaby
#  api_key:
#    secure: 3l827zZPk7wTgnX2eZpc6bYcbOKVQnkB3xOkH43UTIHknJ0IMHrP7S6YNmgIRzkt
#  skip_symbols: true
