-
  branches:
    only:
    - main
  version: 10.0.1-nightly-{build}
  pull_requests:
    do_not_increment_build_number: true
  skip_tags: true
  max_jobs: 1
  image: Visual Studio 2022
  clone_depth: 1
  build_script:
  - ps: |-
      # Version number
      $BUILD_NUMBER = [int]$Env:APPVEYOR_BUILD_NUMBER
      $BUILD_SUFFIX = "nightly"

      # Branch
      $BRANCH = "$Env:APPVEYOR_REPO_BRANCH"
      $Env:DOCFX_SOURCE_BRANCH_NAME = "$BRANCH"

      # Output directory
      $Env:ARTIFACT_DIR = ".\artifacts"
      $dir = New-Item -type directory $env:ARTIFACT_DIR
      $dir = $dir.FullName

      # Verbosity
      Write-Host "Build: $BUILD_NUMBER / Branch: $BRANCH"
      Write-Host "Artifacts will be placed in: $dir"

      # Check if this is a PR
      if (-not $Env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
          Write-Host "Commencing complete build"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER
          & Remove-Item "$dir\*.symbols.nupkg"
      }
      else
      {
          Write-Host "Building from PR ($Env:APPVEYOR_PULL_REQUEST_NUMBER)"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER
          & Remove-Item "$dir\*.symbols.nupkg"
      }
  artifacts:
  - path: artifacts\*.snupkg
  - path: artifacts\*.nupkg
  - path: artifacts\dcs-docs.tar.xz
  deploy:
  - provider: NuGet
    server:
    api_key:
      secure: RjohrwOJE0RgzgIfe71AH42hRr7aZnEz5So/EKRI1FM7LQ/SLrEwSTDsNEQWMQik
    skip_symbols: false
  - provider: GitHub
    auth_token:
      secure: oMF8sv9mhVjO7pBctQOwlmfd5aHQ4hvMoVCz77bgO9+1zBQSelPHxk0bCVfXNCCp
    prerelease: true
    force_update: true
  - provider: NuGet
    server: https://nuget.pkg.github.com/Aiko-IT-Systems/index.json
    username: lulalaby
    api_key:
      secure: SBGo8KrGJ7t5wwMNHKD0WSzrQ+PLJbqXE3FtDH2yGkSrQewO+kzmwp/xGk5a84He
    skip_symbols: true
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
# Releases
-
  branches:
    only:
    - /release/
  version: 10.0.0
  pull_requests:
    do_not_increment_build_number: true
  skip_tags: true
  max_jobs: 1
  image: Visual Studio 2022
  clone_depth: 1
  build_script:
  - ps: |-
      # Version number
      $BUILD_NUMBER = [int]$Env:APPVEYOR_BUILD_NUMBER

      # Branch
      $BRANCH = "$Env:APPVEYOR_REPO_BRANCH"
      $Env:DOCFX_SOURCE_BRANCH_NAME = "$BRANCH"

      # Output directory
      $Env:ARTIFACT_DIR = ".\artifacts"
      $dir = New-Item -type directory $env:ARTIFACT_DIR
      $dir = $dir.FullName

      # Verbosity
      Write-Host "Build: $BUILD_NUMBER / Branch: $BRANCH"
      Write-Host "Artifacts will be placed in: $dir"

      # Check if this is a PR
      if (-not $Env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
          Write-Host "Commencing complete build"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER
          & Remove-Item "$dir\*.symbols.nupkg"
      }
      else
      {
          Write-Host "Building from PR ($Env:APPVEYOR_PULL_REQUEST_NUMBER)"
          & .\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER
          & Remove-Item "$dir\*.symbols.nupkg"
      }
  artifacts:
  - path: artifacts\*.snupkg
  - path: artifacts\*.nupkg
  - path: artifacts\dcs-docs.tar.xz
  deploy:
  - provider: NuGet
    server:
    api_key:
      secure: hFr7dmC41bUWKRLZTu5SpkkN8Xv0b69VdkDL/wcsMkI4RmkVW6GKWi1iUMrtz0IT
    skip_symbols: false
  - provider: GitHub
    auth_token:
      secure: oMF8sv9mhVjO7pBctQOwlmfd5aHQ4hvMoVCz77bgO9+1zBQSelPHxk0bCVfXNCCp
    prerelease: false
    force_update: true
  - provider: NuGet
    server: https://nuget.pkg.github.com/Aiko-IT-Systems/index.json
    username: lulalaby
    api_key:
      secure: SBGo8KrGJ7t5wwMNHKD0WSzrQ+PLJbqXE3FtDH2yGkSrQewO+kzmwp/xGk5a84He
    skip_symbols: true
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
